#!/bin/bash
set -Eeuo pipefail

module load cuda

if [ "$#" -ne  2 ]; then 
    echo "Usage: ./build {filename.cu} {program_name}"
    exit 1
fi
if [ ! -d "libwb/build" ] 
then
    cd libwb/
    mkdir build
    cd build/
    cmake ..
    make -j4
    cd ../..
fi
# module load cuda

nvcc $1 -L$PWD/libwb/build/ -o $2 -I $PWD/libwb/ -std=c++11 -lwb -lnvjpeg -ljpeg -O3 -g -DUSE_COMBINED_KERNEL -DUSE_CONSTANT_MEMORY -DPAGE_LOCK_HOST_BUFFERS -DCOALESCE_GLOBAL_ACCESSES -DSINGLE_GPU_BUFFER -DINPUT_TO_CHAR -DUSE_STREAMS -DOPT_LIST=\"USE_COMBINED_KERNEL___USE_CONSTANT_MEMORY___PAGE_LOCK_HOST_BUFFERS___COALESCE_GLOBAL_ACCESSES___SINGLE_GPU_BUFFER___INPUT_TO_CHAR___USE_STREAMS\"
#-Xcompiler -Ofast -Xcompiler -mavx512f
echo "Successfully built $2"
