#!/bin/bash
# The interpreter used to execute the script

#“#SBATCH” directives that convey submission options:

#SBATCH --job-name=example_job
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=1000m 
#SBATCH --time=01:00
#SBATCH --account=eecs498f21_class
#SBATCH --partition=gpu
#SBATCH --gpus-per-node=1

# The application(s) to execute along with its input arguments and options

export LD_LIBRARY_PATH=$PWD/libwb/build/:$LD_LIBRARY_PATH
TESTNUM=$1

echo "running sequential..."
./parallel.out -i test/$TESTNUM/input.ppm -o test/$TESTNUM/attempt_seq.jpg -t image --parallel
echo "running parallel..."
#nvprof --cpu-profiling on 
./parallel.out -i test/$TESTNUM/input.ppm -o test/$TESTNUM/attempt_par.jpg -t image --parallel --combined

diff test/$TESTNUM/attempt_seq.jpg test/$TESTNUM/attempt_par.jpg