#!/bin/bash
# The interpreter used to execute the script

#“#SBATCH” directives that convey submission options:

#SBATCH --job-name=example_job
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=1000m
#SBATCH --time=01:00
#SBATCH --account=eecs498f21_class
#SBATCH --partition=gpu
#SBATCH --gpus-per-node=1

export LD_LIBRARY_PATH=$PWD/libwb/build/:$LD_LIBRARY_PATH
